name: Release

run-name: Release
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release_project:
    name: Release project
    runs-on: windows-latest
    permissions:
      contents: write
    steps:

    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: true
        fetch-depth: 0

    - name: Get latest tags for tools
      id: tool_tags
      run: |
        $aulua_tag = gh release view --repo karoterra/aviutl2-aulua --json tagName --jq .tagName
        "aulua=$aulua_tag" >> $env:GITHUB_OUTPUT

        $au2cli_tag = gh release view --repo sevenc-nanashi/aviutl2-cli --json tagName --jq .tagName
        "au2cli=$au2cli_tag" >> $env:GITHUB_OUTPUT

        $yq_tag = gh release view --repo mikefarah/yq --json tagName --jq .tagName
        "yq=$yq_tag" >> $env:GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # ----------------------------------------------------
    # キャッシュの復元
    # ----------------------------------------------------
    - name: Restore aulua
      uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: ./aulua
        key: aulua-${{ steps.tool_tags.outputs.aulua }}

    - name: Restore aviutl2-cli
      uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: ./aviutl2-cli
        key: aviutl2-cli-${{ steps.tool_tags.outputs.au2cli }}

    - name: Restore yq
      uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: ./yq
        key: yq-${{ steps.tool_tags.outputs.yq }}

    # ----------------------------------------------------
    # 各ツールのパスを通す
    # ----------------------------------------------------
    - name: Setup tools
      run: |
        cd ./yq
        Copy-Item *.exe yq.exe
        echo "$(Get-Location)" >> $env:GITHUB_PATH

        cd ../aulua
        echo "$(Get-Location)" >> $env:GITHUB_PATH

        cd ../aviutl2-cli
        Copy-Item *.exe au2.exe
        echo "$(Get-Location)" >> $env:GITHUB_PATH

    - name: Extract version
      id: extract-version
      run: |
        $version = "$env:GITHUB_REF_NAME".TrimStart('v')
        echo "version=$version" >> $env:GITHUB_OUTPUT

    # aulua の VERSION 変数を置き換える
    - name: aulua variable update
      run: |
        $version = "v$env:VERSION"
        yq -i ".project.variables.VERSION = `"$version`"" ./script/aulua.yaml
      env:
        VERSION: ${{ steps.extract-version.outputs.version }}

    # CMakePresets.json の PLUGIN_VERSION 変数を置き換える
    - name: CMakePresets.json variable update
      run: |
        $version = "v$env:VERSION"
        yq -i '(.configurePresets[] | select(.name == \"windows-base\")).cacheVariables.PLUGIN_VERSION = `"$version`"" ./CMakePresets.json
      env:
        VERSION: ${{ steps.extract-version.outputs.version }}

    # ----------------------------------------------------
    # ビルド & リリース
    # ----------------------------------------------------
    - name: Build project
      run: |
        mkdir release
        cargo set-version "$env:VERSION"
        au2 release --set-version "$env:VERSION"
      env:
        VERSION: ${{ steps.extract-version.outputs.version }}

    - name: Commit version change
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add aulua.yaml CMakePresets.json
        git commit -m "feat: update config files version v$env:VERSION"
        git branch
        git push origin HEAD:main
      env:
        VERSION: ${{ steps.extract-version.outputs.version }}

    - name: Create release notes
      run: |
        dotnet .\tools\ChangelogExtract.cs -- .\CHANGELOG.md .\EXTRACTED.md --semver "$env:VERSION"
        Move-Item -Path release\*-$env:VERSION.au2pkg.zip -Destination .\
        gh release create "v$env:VERSION" --notes-file EXTRACTED.md "*.au2pkg.zip"
      env:
        VERSION: ${{ steps.extract-version.outputs.version }}
